### ISSUE TITLE
Support shader models?

### ISSUE THREAD

**Issue by PaddiM** [NVlabs/fermat#3]
I can't compile Fermat 2.0 with sm_61,compute_61 for GTX 1070:

3>D:\Projekte\3D\NVidia\fermat\src\pathtracer_core.h(550): error : identifier "__match_all_sync" is undefined

Is this expected and Fermat should only work with RTX cards?

**Comment by Woking-34** [comment]
Hi, the latest master with commits from yesterday fix the Pascal compatibility.

**Comment by PaddiM** [comment]
Thanks. Works like a charm!

**Comment by jpantaleoni** [comment]
Glad to hear!
